-- ============================================================================
-- DML 001: Initial seed data
-- Run AFTER all DDL migrations are applied.
-- Safe to re-run — uses ON CONFLICT DO NOTHING.
-- ============================================================================
SET search_path TO public;

-- ── Company ──────────────────────────────────────────────────────────────────
INSERT INTO company (company_name, email, website, is_active, created_at, updated_at)
VALUES ('MyActivity', 'admin@myactivity.in', 'https://myactivity.in', 1, NOW(), NOW())
ON CONFLICT DO NOTHING;

-- ── Project ──────────────────────────────────────────────────────────────────
INSERT INTO project (project_name, project_code, is_active, created_at, updated_at)
VALUES ('MyActivity Project', 'MA-001', 1, NOW(), NOW())
ON CONFLICT (project_code) DO NOTHING;

-- ── Designations ─────────────────────────────────────────────────────────────
INSERT INTO designation (designation, project_id, is_active, created_at, updated_at)
SELECT d.designation, p.project_id, 1, NOW(), NOW()
FROM (VALUES
  ('Field Officer'),
  ('Block Coordinator'),
  ('District Manager'),
  ('Project Manager'),
  ('Data Entry Operator')
) AS d(designation)
CROSS JOIN project p
WHERE p.project_code = 'MA-001'
ON CONFLICT (designation) DO NOTHING;

-- ── Demo User (password: Pass@123) ───────────────────────────────────────────
-- Note: password hash is bcrypt of 'Pass@123' with 10 rounds
INSERT INTO user_tbl (emp_code, full_name, date_of_birth, gender, mobile_number, email, nationality, is_active, created_at, updated_at)
VALUES ('EMP-001', 'John Doe', '1990-01-01', 'Male', '9999999999', 'john@myactivity.in', 'Indian', 1, NOW(), NOW())
ON CONFLICT (emp_code) DO NOTHING;

-- user_information (linked to user + company)
INSERT INTO user_information (user_id, company_id, is_active, created_at, updated_at)
SELECT u.user_id, c.company_id, 1, NOW(), NOW()
FROM user_tbl u, company c
WHERE u.emp_code = 'EMP-001' AND c.company_name = 'MyActivity'
ON CONFLICT (user_id) DO NOTHING;

-- user_login  — hash generated by:  bcrypt.hashSync('Pass@123', 10)
INSERT INTO user_login (user_id, mobile_number, password, company_id, is_active, created_at, updated_at)
SELECT u.user_id, '9999999999',
       '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
       c.company_id, 1, NOW(), NOW()
FROM user_tbl u, company c
WHERE u.emp_code = 'EMP-001' AND c.company_name = 'MyActivity'
ON CONFLICT (user_id) DO NOTHING;
